# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
on:
  pull_request:
    branches: [ "main" ]
name: Test
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Download Dependencies
      run: go mod download
    - name: Install dependencies
      run: go get .
    - name: Run Go Tests with Coverage
      run: go test -v ./...
